### ISSUE TITLE
use of distanceText in updateLocation in scenemanager

### ISSUE THREAD

**Issue by TedBausch** [dartmouth-cs98/18w-hikar-frontend#55]
I like how this function is separate from the actual updating of the gps location and handles the movement of the camera by moving the player. 

Does distanceText get used in any meaningful way in this function? It looks like it gets updated elsewhere and is just being set to a test value in the function, so it might be better to just leave it alone.

**Comment by 0wang1** [comment]
distanceText is used as a debug text for when we're trying to debug the application on mobile. It will be removed before the presentation at the end of the term following release
