### ISSUE TITLE
how the trail search results are displayed

### ISSUE THREAD

**Issue by MPhilie** [dartmouth-cs98/18w-hikar-frontend#58]
https://github.com/dartmouth-cs98/18w-hikar-frontend/blob/6f9a7316f3fa8223116beccd33b9892bf6ab532e/Assets/topoScene/UIManager.cs#L45

I understand how you are searching you're trails list (currently just a hardcoded list) for results that match the search in the function onValueChangedSearch(), but where are you displaying this resultsList? And what if they don't spell a trail correctly? If the search does not contain, is it close to a trail name? ...not sure how hard that'd be to implement a "sounds like" search for not knowing the exact name of a trail

**Comment by 0wang1** [comment]
Good point, I'll fix it so that it does an auto search every time the input is being changed. This will help indicate to the user that something is misspelled when all the results suddenly disappear
