### ISSUE TITLE
better way for this

### ISSUE THREAD

**Issue by MPhilie** [dartmouth-cs98/18w-hikar-frontend#59]
https://github.com/dartmouth-cs98/18w-hikar-frontend/blob/398293b70c39d8762990b3b888f1322fc3092765/Assets/topoScene/SceneManager.cs#L13

Is there a better way than having 54 lines of public variables here?

**Comment by 0wang1** [comment]
https://answers.unity.com/questions/28050/how-to-group-variables-in-the-inspector.html
Not sure if this was what you were suggesting... did you have any ideas? Closing this for now
